### ISSUE TITLE
[Doc] Async worker example

### ISSUE THREAD

**Issue by melkir** [jcs224/faktory_worker_deno#1]
Thanks for this library, could you show me an example using an async function? How to avoid the job to be terminated immediately?

```
import {
  FaktoryClient,
  FaktoryJob,
} from "https://deno.land/x/faktory_worker_deno@v0.1.6/mod.ts";

function timeout(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function randomIntFromInterval(min: number, max: number) {
  // min and max included
  await timeout(5000);
  return Math.floor(Math.random() * (max - min + 1) + min);
}

const client = new FaktoryClient("localhost", 7419);
await client.connect();

// Create job
const job = new FaktoryJob("adder", [
  randomIntFromInterval(1, 10),
  randomIntFromInterval(1, 10),
]);
// Push job
await client.push(job);

client.close();
```

```
# client.ts
# deno run -A client.ts

import { FaktoryClient, FaktoryWorker } from "./deps.ts";

const PORT = 7419;
const client = new FaktoryClient("localhost", PORT);
await client.connect();

console.log(`Listening on http://localhost:${PORT}`);

const worker = new FaktoryWorker(client);

worker.register("validate", (job: unknown) => {
  console.log(job);
});

await worker.run(true);
```

```
Listening on http://localhost:7419
[ {}, {} ]
```

**Comment by jcs224** [comment]
So, if you're feeding an async first-class function as an argument, you'll need to put `await` in front of it when it's called.

```js
// Create job
const job = new FaktoryJob("adder", [
  await randomIntFromInterval(1, 10),
  await randomIntFromInterval(1, 10),
]);
``` 

In the worker, when registering a job, just put `async` in front of the function.

```js
worker.register('adder', async (job) => {
  await new Promise(resolve => setTimeout(resolve, 3000))
  console.log(job)
  console.log('args added together: '+ (job[0] + job[1]))
 }
```

**Comment by melkir** [comment]
Thanks @jcs224 for your answer.

What I'm looking for is the ability to place a time-consuming job in a process, while having the ability to notify the client once the job is complete. Finally I came to the conclusion that I should simply place the calculation part on the client side, because otherwise I would risk blocking the server. The only problem is that it is impossible to follow its success or failure from the Faktory dashboard.

If you're wondering what is my use-case, here's the opensource projet I'm working on https://github.com/melkir/dsn-validator.

Also if you need help for adding some typescript types to this projet, it would be a pleasure to submit a PR 😁

**Comment by jcs224** [comment]
@melkir thanks for the input! I will happily take a types PR if you submit one. As you can probably tell, this library was created a long time ago and hasn't really seen maintenance. Glad it's still working through the Deno and Faktory upgrades. I'm only now sort of learning TypeScript.

I'm not certain about the reliability of the async functions. I played with it a little last night and it wasn't running every single time a job was pushed.

That said, very open to contributions.

**Comment by melkir** [comment]
Looking at the https://github.com/jbielick/faktory_worker_node version, they might be a way to adapt the code from there. Ideally having a `faktory_worker_js` version that works on both `node` and `deno` would be awesome 🤞

**Comment by jcs224** [comment]
@melkir that would be nice, I agree. Unfortunately Node and Deno use different APIs for making raw TCP connections, that's probably the biggest hurdle preventing cross-compatibility. Deno has a Node compatibility layer but I don't think it includes `net`, which I believe is the standard way to create a TCP connection in Node.

Would probably be worth seeing how they do it and incorporate that stuff for the edge cases we're running into though.

**Comment by jcs224** [comment]
Well, when this lands in Deno standard library, I will test it and see if it works with the node library. If it does, I will archive this project and recommend using the Node one.

https://github.com/denoland/deno_std/pull/1375

**Comment by melkir** [comment]
Hello @jcs224, look like it has landed. I'm rather curious as to how you plan to test this compatibility.

**Comment by jcs224** [comment]
@melkir I've been trying to run the worker as Deno gets updates, but it's not quite working with Faktory yet. Deno-Node compatibility isn't quite there.

However, if you just want to *push* jobs from Deno, and execute the jobs in Node, this should be possible using this library to push jobs (including from Deno Deploy), and using a Node runtime to execute Node jobs. That is the beauty of Faktory after all :smile:

**Comment by jcs224** [comment]
here you go @melkir https://github.com/jbielick/faktory_worker_node/issues/224#issuecomment-1035842820
